import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { AlertTriangle, ArchiveRestore, Boxes, CalendarClock, CircleDollarSign, PackageCheck, PackagePlus, Plus, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

const db = supabase as any;
type Stock = { item_id:string; name:string; category:string; unit:string; minimum_stock:number; expiry_warning_days:number; notes?:string; active:boolean; current_stock:number; nearest_expiry?:string };
type Batch = { id:string; item_id:string; quantity_received:number; quantity_remaining:number; total_cost:number; unit_cost:number; purchased_on:string; expires_on?:string; supplier?:string; created_at:string };
type Consumption = { id:string; item_id:string; barber_id:string; consumption_date:string; quantity:number; notes?:string; status:string; created_at:string; reversal_reason?:string };

const money = (value:number) => value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const num = (value:number) => Number(value || 0).toLocaleString('pt-BR',{maximumFractionDigits:3});
const today = () => new Date().toISOString().slice(0,10);

export default function SupplyInventoryManager() {
  const [stock,setStock]=useState<Stock[]>([]); const [batches,setBatches]=useState<Batch[]>([]); const [consumptions,setConsumptions]=useState<Consumption[]>([]);
  const [movements,setMovements]=useState<any[]>([]);
  const [barbers,setBarbers]=useState<any[]>([]); const [allocations,setAllocations]=useState<any[]>([]); const [loading,setLoading]=useState(true);
  const [itemOpen,setItemOpen]=useState(false); const [batchOpen,setBatchOpen]=useState(false); const [saving,setSaving]=useState(false);
  const [consumptionOpen,setConsumptionOpen]=useState(false);
  const [settings,setSettings]=useState({whatsapp_enabled:true,expiry_warning_days:15});
  const [item,setItem]=useState({name:'',category:'Geral',unit:'unidade',minimum_stock:'0',expiry_warning_days:'15',notes:''});
  const [batch,setBatch]=useState({item_id:'',quantity:'',unit_cost:'',purchased_on:today(),expires_on:'',supplier:'',invoice_reference:'',notes:''});
  const [managementConsumption,setManagementConsumption]=useState({item_id:'',barber_id:'',quantity:'',consumption_date:today(),notes:''});
  const [query,setQuery]=useState('');

  const load=useCallback(async()=>{
    setLoading(true);
    const [s,b,c,a,br,cfg,m]=await Promise.all([
      db.rpc('get_supply_stock'), db.from('supply_batches').select('*').order('created_at',{ascending:false}),
      db.from('supply_consumptions').select('*').order('consumption_date',{ascending:false}).limit(500),
      db.from('supply_consumption_allocations').select('*'), db.from('barbers').select('id,name'),
      db.from('site_config').select('config_value').eq('config_key','supply_inventory').maybeSingle(),
      db.from('supply_movements').select('*').order('created_at',{ascending:false}).limit(1000)
    ]);
    const error=s.error||b.error||c.error||a.error||br.error;
    if(error) toast.error('Erro ao carregar estoque',{description:error.message});
    setStock(s.data||[]); setBatches(b.data||[]); setConsumptions(c.data||[]); setAllocations(a.data||[]); setBarbers(br.data||[]); setMovements(m.data||[]);
    if(cfg.data?.config_value) setSettings({...settings,...cfg.data.config_value});
    setLoading(false);
  },[]);
  useEffect(()=>{ load(); const channel=supabase.channel('supply-admin-live').on('postgres_changes',{event:'*',schema:'public',table:'supply_items'},load).on('postgres_changes',{event:'*',schema:'public',table:'supply_batches'},load).on('postgres_changes',{event:'*',schema:'public',table:'supply_consumptions'},load).subscribe(); return()=>{supabase.removeChannel(channel)}; },[load]);

  const metrics=useMemo(()=>{
    const now=today(); const warning=new Date(); warning.setDate(warning.getDate()+settings.expiry_warning_days); const warningDate=warning.toISOString().slice(0,10);
    const invested=batches.reduce((t,b)=>t+Number(b.quantity_remaining)*Number(b.unit_cost),0);
    const costByConsumption=new Map<string,number>(); allocations.forEach(a=>costByConsumption.set(a.consumption_id,(costByConsumption.get(a.consumption_id)||0)+Number(a.quantity)*Number(a.unit_cost)));
    const month=today().slice(0,7); const consumed=consumptions.filter(c=>c.status==='active'&&c.consumption_date.startsWith(month)).reduce((t,c)=>t+(costByConsumption.get(c.id)||0),0);
    return {active:stock.filter(x=>x.active).length,invested,low:stock.filter(x=>x.active&&Number(x.current_stock)<=Number(x.minimum_stock)).length,near:batches.filter(x=>Number(x.quantity_remaining)>0&&x.expires_on&&x.expires_on>=now&&x.expires_on<=warningDate).length,expired:batches.filter(x=>Number(x.quantity_remaining)>0&&x.expires_on&&x.expires_on<now).length,consumed};
  },[stock,batches,consumptions,allocations,settings.expiry_warning_days]);
  const names=Object.fromEntries(stock.map(x=>[x.item_id,x.name])); const barberNames=Object.fromEntries(barbers.map(x=>[x.id,x.name]));
  const visibleStock=stock.filter(x=>`${x.name} ${x.category}`.toLowerCase().includes(query.toLowerCase()));

  async function saveItem(){ setSaving(true); const {data:{user}}=await supabase.auth.getUser(); const {error}=await db.from('supply_items').insert({name:item.name.trim(),category:item.category.trim()||'Geral',unit:item.unit.trim()||'unidade',minimum_stock:Number(item.minimum_stock),expiry_warning_days:Number(item.expiry_warning_days),notes:item.notes.trim()||null,created_by:user?.id}); setSaving(false); if(error)return toast.error('Não foi possível cadastrar',{description:error.message}); toast.success('Insumo cadastrado'); setItemOpen(false); setItem({name:'',category:'Geral',unit:'unidade',minimum_stock:'0',expiry_warning_days:'15',notes:''}); load(); }
  async function saveBatch(){ setSaving(true); const totalCost=Number(batch.quantity)*Number(batch.unit_cost); const {error}=await db.rpc('create_supply_batch',{p_item_id:batch.item_id,p_quantity:Number(batch.quantity),p_total_cost:totalCost,p_purchased_on:batch.purchased_on,p_expires_on:batch.expires_on||null,p_supplier:batch.supplier||null,p_invoice_reference:batch.invoice_reference||null,p_notes:batch.notes||null}); setSaving(false); if(error)return toast.error('Não foi possível registrar a entrada',{description:error.message}); toast.success('Entrada registrada e saldo atualizado'); setBatchOpen(false); load(); }
  async function reverse(c:Consumption){ const reason=window.prompt('Motivo obrigatório do estorno:'); if(!reason?.trim())return; const {error}=await db.rpc('reverse_supply_consumption',{p_consumption_id:c.id,p_reason:reason.trim()}); if(error)return toast.error('Falha no estorno',{description:error.message}); toast.success('Consumo estornado'); load(); }
  async function saveManagementConsumption(){ setSaving(true); const {error}=await db.rpc('record_supply_consumption',{p_item_id:managementConsumption.item_id,p_quantity:Number(managementConsumption.quantity),p_consumption_date:managementConsumption.consumption_date,p_notes:managementConsumption.notes||null,p_idempotency_key:crypto.randomUUID(),p_barber_id:managementConsumption.barber_id}); setSaving(false); if(error)return toast.error('Não foi possível registrar o consumo',{description:error.message}); toast.success('Consumo registrado para o barbeiro'); setConsumptionOpen(false); setManagementConsumption({item_id:'',barber_id:'',quantity:'',consumption_date:today(),notes:''}); load(); }
  async function saveSettings(){ const {error}=await db.from('site_config').upsert({config_key:'supply_inventory',config_value:settings},{onConflict:'config_key'}); if(error)return toast.error('Falha ao salvar alertas',{description:error.message}); toast.success('Configurações de estoque salvas'); }

  const cards=[['Itens ativos',metrics.active,Boxes],['Valor investido',money(metrics.invested),CircleDollarSign],['Abaixo do mínimo',metrics.low,AlertTriangle],['Próximos do vencimento',metrics.near,CalendarClock],['Lotes vencidos',metrics.expired,AlertTriangle],['Consumido no mês',money(metrics.consumed),ArchiveRestore]] as const;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold sm:text-2xl">Estoque de Insumos</h1><p className="text-xs text-muted-foreground sm:text-sm">Controle de lotes, consumo, custos e validade separado do shop.</p></div><div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><Button size="sm" variant="outline" onClick={load}><RefreshCw className="mr-1 h-4 w-4 sm:mr-2"/>Atualizar</Button><Button size="sm" variant="outline" onClick={()=>setItemOpen(true)}><Plus className="mr-1 h-4 w-4 sm:mr-2"/>Novo insumo</Button><Button size="sm" className="col-span-2 sm:col-span-1" onClick={()=>setBatchOpen(true)}><PackagePlus className="mr-1 h-4 w-4 sm:mr-2"/>Registrar entrada</Button></div></div>
    <div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{cards.map(([title,value,Icon])=><Card key={title}><CardContent className="p-3"><div className="flex justify-between gap-2"><div><p className="text-[11px] text-muted-foreground sm:text-xs">{title}</p><p className="mt-1 text-lg font-bold sm:text-xl">{value}</p></div><Icon className="h-4 w-4 text-primary"/></div></CardContent></Card>)}</div>
    <Tabs defaultValue="stock"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 p-1 sm:flex sm:w-auto sm:flex-wrap"><TabsTrigger className="text-xs sm:text-sm" value="stock">Estoque atual</TabsTrigger><TabsTrigger className="text-xs sm:text-sm" value="batches">Entradas e lotes</TabsTrigger><TabsTrigger className="text-xs sm:text-sm" value="consumption">Consumo</TabsTrigger><TabsTrigger className="text-xs sm:text-sm" value="history">Histórico</TabsTrigger><TabsTrigger className="col-span-2 text-xs sm:text-sm" value="settings">Configurações</TabsTrigger></TabsList>
      <TabsContent value="stock" className="space-y-3"><Input className="h-10" placeholder="Pesquisar item ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/><div className="grid grid-cols-1 gap-2 sm:hidden">{visibleStock.map(x=>{const low=Number(x.current_stock)<=Number(x.minimum_stock);return <Card key={x.item_id} className="overflow-hidden"><CardContent className="p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="break-words text-sm font-semibold leading-tight">{x.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{x.category}</p></div><Badge className="shrink-0 text-[10px]" variant={low?'destructive':'secondary'}>{x.active?(low?'Baixo':'Regular'):'Inativo'}</Badge></div><div className="mt-3 grid grid-cols-2 gap-2 rounded-md bg-muted/30 p-2"><div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Saldo</p><p className="text-sm font-bold">{num(x.current_stock)} <span className="text-[11px] font-normal">{x.unit}</span></p></div><div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Mínimo</p><p className="text-sm font-semibold">{num(x.minimum_stock)} <span className="text-[11px] font-normal">{x.unit}</span></p></div></div><p className="mt-2 text-[11px] text-muted-foreground">Validade mais próxima: <span className="text-foreground">{x.nearest_expiry?new Date(`${x.nearest_expiry}T12:00:00`).toLocaleDateString('pt-BR'):'Sem validade'}</span></p></CardContent></Card>})}</div><div className="hidden rounded-lg border overflow-x-auto sm:block"><Table><TableHeader><TableRow><TableHead>Insumo</TableHead><TableHead>Categoria</TableHead><TableHead>Saldo</TableHead><TableHead>Mínimo</TableHead><TableHead>Próxima validade</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{visibleStock.map(x=><TableRow key={x.item_id}><TableCell className="font-medium">{x.name}</TableCell><TableCell>{x.category}</TableCell><TableCell>{num(x.current_stock)} {x.unit}</TableCell><TableCell>{num(x.minimum_stock)}</TableCell><TableCell>{x.nearest_expiry?new Date(`${x.nearest_expiry}T12:00:00`).toLocaleDateString('pt-BR'):'Sem validade'}</TableCell><TableCell><Badge variant={Number(x.current_stock)<=Number(x.minimum_stock)?'destructive':'secondary'}>{x.active?(Number(x.current_stock)<=Number(x.minimum_stock)?'Estoque baixo':'Regular'):'Inativo'}</Badge></TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
      <TabsContent value="batches"><div className="rounded-lg border overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Compra</TableHead><TableHead>Saldo do lote</TableHead><TableHead>Custo unitário</TableHead><TableHead>Investido restante</TableHead><TableHead>Validade</TableHead><TableHead>Fornecedor</TableHead></TableRow></TableHeader><TableBody>{batches.map(b=><TableRow key={b.id}><TableCell>{names[b.item_id]||b.item_id}</TableCell><TableCell>{new Date(`${b.purchased_on}T12:00:00`).toLocaleDateString('pt-BR')}</TableCell><TableCell>{num(b.quantity_remaining)} / {num(b.quantity_received)}</TableCell><TableCell>{money(Number(b.unit_cost))}</TableCell><TableCell>{money(Number(b.quantity_remaining)*Number(b.unit_cost))}</TableCell><TableCell>{b.expires_on?new Date(`${b.expires_on}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</TableCell><TableCell>{b.supplier||'—'}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
      <TabsContent value="consumption" className="space-y-3"><div className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">Consumo individual dos barbeiros</p><p className="text-xs text-muted-foreground">O barbeiro pode lançar no próprio painel ou a gestão pode registrar em nome dele.</p></div><Button size="sm" onClick={()=>setConsumptionOpen(true)}><PackageCheck className="mr-2 h-4 w-4"/>Registrar para barbeiro</Button></div><div className="rounded-lg border overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Insumo</TableHead><TableHead>Quantidade</TableHead><TableHead>Barbeiro</TableHead><TableHead>Custo</TableHead><TableHead>Observação</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{consumptions.map(c=>{const cost=allocations.filter(a=>a.consumption_id===c.id).reduce((t,a)=>t+Number(a.quantity)*Number(a.unit_cost),0);return <TableRow key={c.id}><TableCell>{new Date(`${c.consumption_date}T12:00:00`).toLocaleDateString('pt-BR')}</TableCell><TableCell>{names[c.item_id]}</TableCell><TableCell>{num(c.quantity)}</TableCell><TableCell>{barberNames[c.barber_id]}</TableCell><TableCell>{money(cost)}</TableCell><TableCell>{c.notes||'—'}</TableCell><TableCell><Badge variant={c.status==='reversed'?'outline':'secondary'}>{c.status==='reversed'?'Estornado':'Ativo'}</Badge></TableCell><TableCell>{c.status==='active'&&<Button size="sm" variant="outline" onClick={()=>reverse(c)}>Estornar</Button>}</TableCell></TableRow>})}</TableBody></Table></div></TabsContent>
      <TabsContent value="history"><p className="mb-3 text-sm text-muted-foreground">Auditoria completa preservada nas movimentações de entrada, consumo e estorno.</p><div className="rounded-lg border overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Movimentação</TableHead><TableHead>Insumo</TableHead><TableHead>Quantidade</TableHead><TableHead>Barbeiro</TableHead><TableHead>Custo</TableHead><TableHead>Observação</TableHead></TableRow></TableHeader><TableBody>{movements.map(m=><TableRow key={m.id}><TableCell>{new Date(`${m.movement_date}T12:00:00`).toLocaleDateString('pt-BR')}</TableCell><TableCell><Badge variant={m.movement_type==='reversal'?'outline':'secondary'}>{{entry:'Entrada',consumption:'Consumo',adjustment_in:'Ajuste de entrada',adjustment_out:'Ajuste de saída',reversal:'Estorno'}[m.movement_type]||m.movement_type}</Badge></TableCell><TableCell>{names[m.item_id]||m.item_id}</TableCell><TableCell>{num(m.quantity)}</TableCell><TableCell>{m.barber_id?barberNames[m.barber_id]||'Barbeiro':'Gestão'}</TableCell><TableCell>{money(Number(m.quantity)*Number(m.unit_cost))}</TableCell><TableCell>{m.notes||'—'}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
      <TabsContent value="settings"><Card><CardHeader><CardTitle>Alertas administrativos</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between rounded-lg border p-4"><div><p className="font-medium">Alertas de estoque pelo WhatsApp</p><p className="text-sm text-muted-foreground">Usa o número administrativo configurado nos relatórios.</p></div><Switch checked={settings.whatsapp_enabled} onCheckedChange={v=>setSettings({...settings,whatsapp_enabled:v})}/></div><div className="max-w-xs"><Label>Antecedência padrão de validade (dias)</Label><Input type="number" min="0" max="365" value={settings.expiry_warning_days} onChange={e=>setSettings({...settings,expiry_warning_days:Number(e.target.value)})}/></div><Button onClick={saveSettings}>Salvar configurações</Button></CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={itemOpen} onOpenChange={setItemOpen}><DialogContent><DialogHeader><DialogTitle>Novo insumo</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div><Label>Nome</Label><Input value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></div><div><Label>Categoria</Label><Input value={item.category} onChange={e=>setItem({...item,category:e.target.value})}/></div><div><Label>Unidade de medida</Label><Input placeholder="unidade, pacote, kg..." value={item.unit} onChange={e=>setItem({...item,unit:e.target.value})}/></div><div><Label>Estoque mínimo</Label><Input type="number" step="0.001" value={item.minimum_stock} onChange={e=>setItem({...item,minimum_stock:e.target.value})}/></div><div><Label>Alerta de validade (dias)</Label><Input type="number" value={item.expiry_warning_days} onChange={e=>setItem({...item,expiry_warning_days:e.target.value})}/></div><div className="sm:col-span-2"><Label>Observações</Label><Textarea value={item.notes} onChange={e=>setItem({...item,notes:e.target.value})}/></div></div><Button disabled={saving||!item.name.trim()} onClick={saveItem}>Cadastrar insumo</Button></DialogContent></Dialog>
    <Dialog open={batchOpen} onOpenChange={setBatchOpen}><DialogContent><DialogHeader><DialogTitle>Registrar entrada / lote</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Insumo</Label><Select value={batch.item_id} onValueChange={v=>setBatch({...batch,item_id:v})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{stock.filter(x=>x.active).map(x=><SelectItem key={x.item_id} value={x.item_id}>{x.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantidade</Label><Input type="number" step="0.001" value={batch.quantity} onChange={e=>setBatch({...batch,quantity:e.target.value})}/></div><div><Label>Custo unitário (R$)</Label><Input type="number" min="0" step="0.01" value={batch.unit_cost} onChange={e=>setBatch({...batch,unit_cost:e.target.value})}/><p className="mt-1 text-xs text-muted-foreground">Valor pago por cada unidade.</p></div><div className="sm:col-span-2 rounded-md border bg-muted/30 p-3"><p className="text-xs text-muted-foreground">Custo total do lote</p><p className="text-lg font-bold text-primary">{money(Number(batch.quantity||0)*Number(batch.unit_cost||0))}</p></div><div><Label>Data da compra</Label><Input type="date" value={batch.purchased_on} onChange={e=>setBatch({...batch,purchased_on:e.target.value})}/></div><div><Label>Validade (opcional)</Label><Input type="date" value={batch.expires_on} onChange={e=>setBatch({...batch,expires_on:e.target.value})}/></div><div><Label>Fornecedor</Label><Input value={batch.supplier} onChange={e=>setBatch({...batch,supplier:e.target.value})}/></div><div><Label>Nota / referência</Label><Input value={batch.invoice_reference} onChange={e=>setBatch({...batch,invoice_reference:e.target.value})}/></div><div className="sm:col-span-2"><Label>Observações</Label><Textarea value={batch.notes} onChange={e=>setBatch({...batch,notes:e.target.value})}/></div></div><Button disabled={saving||!batch.item_id||Number(batch.quantity)<=0||Number(batch.unit_cost)<0||batch.unit_cost===''} onClick={saveBatch}>Confirmar entrada</Button></DialogContent></Dialog>
    <Dialog open={consumptionOpen} onOpenChange={setConsumptionOpen}><DialogContent><DialogHeader><DialogTitle>Registrar consumo para barbeiro</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Use apenas quando a gestão quiser lançar a saída. O barbeiro também pode fazer o próprio registro no painel dele.</p><div className="grid gap-3 sm:grid-cols-2"><div><Label>Barbeiro responsável</Label><Select value={managementConsumption.barber_id} onValueChange={v=>setManagementConsumption({...managementConsumption,barber_id:v})}><SelectTrigger><SelectValue placeholder="Selecione o barbeiro"/></SelectTrigger><SelectContent>{barbers.map(b=><SelectItem key={b.id} value={b.id}>{b.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Insumo utilizado</Label><Select value={managementConsumption.item_id} onValueChange={v=>setManagementConsumption({...managementConsumption,item_id:v})}><SelectTrigger><SelectValue placeholder="Selecione o insumo"/></SelectTrigger><SelectContent>{stock.filter(x=>x.active&&Number(x.current_stock)>0).map(x=><SelectItem key={x.item_id} value={x.item_id}>{x.name} — {num(x.current_stock)} {x.unit}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantidade consumida</Label><Input type="number" min="0.001" step="0.001" value={managementConsumption.quantity} onChange={e=>setManagementConsumption({...managementConsumption,quantity:e.target.value})}/></div><div><Label>Data do consumo</Label><Input type="date" max={today()} value={managementConsumption.consumption_date} onChange={e=>setManagementConsumption({...managementConsumption,consumption_date:e.target.value})}/></div><div className="sm:col-span-2"><Label>Observação (opcional)</Label><Textarea placeholder="Ex.: uso individual, limpeza de equipamento..." value={managementConsumption.notes} onChange={e=>setManagementConsumption({...managementConsumption,notes:e.target.value})}/></div></div><Button disabled={saving||!managementConsumption.barber_id||!managementConsumption.item_id||Number(managementConsumption.quantity)<=0} onClick={saveManagementConsumption}>Confirmar consumo</Button></DialogContent></Dialog>
    {loading&&<p className="text-sm text-muted-foreground">Atualizando estoque…</p>}
  </div>;
}
