import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import { ChevronDown, ChevronUp, PackageCheck, PackageOpen } from 'lucide-react';
import { toast } from 'sonner';

const db=supabase as any;
const iso=(date:Date)=>date.toISOString().slice(0,10);
export default function SupplyConsumptionPanel({barberId}:{barberId:string}){
  const now=new Date(); const yesterday=new Date(now); yesterday.setDate(now.getDate()-1);
  const allowed=[iso(now),iso(yesterday)]; const [stock,setStock]=useState<any[]>([]); const [history,setHistory]=useState<any[]>([]);
  const [showAllStock,setShowAllStock]=useState(false);
  const [form,setForm]=useState({item_id:'',quantity:'',consumption_date:allowed[0],notes:''}); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{const [s,h]=await Promise.all([db.rpc('get_supply_stock'),db.from('supply_consumptions').select('id,item_id,consumption_date,quantity,notes,status,created_at').eq('barber_id',barberId).order('consumption_date',{ascending:false}).limit(60)]); if(s.error||h.error)toast.error('Falha ao carregar insumos',{description:(s.error||h.error).message}); setStock((s.data||[]).filter((x:any)=>x.active)); setHistory(h.data||[]);},[barberId]);
  useEffect(()=>{load();const ch=supabase.channel(`supply-barber-${barberId}`).on('postgres_changes',{event:'*',schema:'public',table:'supply_batches'},load).on('postgres_changes',{event:'*',schema:'public',table:'supply_consumptions'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[barberId,load]);
  const names=Object.fromEntries(stock.map(x=>[x.item_id,x.name]));
  const availableStock=stock.filter(x=>Number(x.current_stock)>0);
  async function submit(){setSaving(true);const {error}=await db.rpc('record_supply_consumption',{p_item_id:form.item_id,p_quantity:Number(form.quantity),p_consumption_date:form.consumption_date,p_notes:form.notes||null,p_idempotency_key:crypto.randomUUID(),p_barber_id:barberId});setSaving(false);if(error)return toast.error('Consumo não registrado',{description:error.message});toast.success('Consumo registrado e estoque atualizado');setForm({...form,item_id:'',quantity:'',notes:''});load();}
  return <div className="space-y-4 sm:space-y-5"><div className="rounded-xl border border-primary/20 bg-gradient-to-r from-primary/10 to-transparent p-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-primary/15 p-2"><PackageCheck className="h-5 w-5 text-primary"/></div><div><h2 className="text-xl font-bold sm:text-2xl">Consumo de Insumos</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground sm:text-sm">Registre o que você utilizou hoje ou ontem. Os valores dos produtos ficam visíveis somente para a gestão.</p></div></div></div>
  <Card className="border-primary/25"><CardHeader className="p-4 pb-2"><CardTitle className="text-base sm:text-lg">Registrar consumo diário</CardTitle></CardHeader><CardContent className="grid gap-3 p-4 pt-2 md:grid-cols-4"><div className="md:col-span-2"><Label>Insumo utilizado</Label><Select value={form.item_id} onValueChange={v=>setForm({...form,item_id:v})}><SelectTrigger className="h-11"><SelectValue placeholder={availableStock.length?'Selecione o insumo':'Nenhum item disponível'}/></SelectTrigger><SelectContent>{availableStock.map(x=><SelectItem key={x.item_id} value={x.item_id}>{x.name} — {Number(x.current_stock).toLocaleString('pt-BR')} {x.unit}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantidade</Label><Input className="h-11" type="number" min="0.001" step="0.001" placeholder="0" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></div><div><Label>Dia do consumo</Label><Select value={form.consumption_date} onValueChange={v=>setForm({...form,consumption_date:v})}><SelectTrigger className="h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={allowed[0]}>Hoje</SelectItem><SelectItem value={allowed[1]}>Ontem</SelectItem></SelectContent></Select></div><div className="md:col-span-3"><Label>Observação (opcional)</Label><Textarea className="min-h-20" placeholder="Ex.: troca de lâmina, limpeza do equipamento..." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="flex items-end"><Button className="h-11 w-full" disabled={saving||!form.item_id||Number(form.quantity)<=0} onClick={submit}>Confirmar consumo</Button></div>{availableStock.length===0&&<div className="md:col-span-4 flex items-center gap-2 rounded-lg border border-dashed p-3 text-xs text-muted-foreground"><PackageOpen className="h-4 w-4"/>Ainda não há insumos com saldo disponível. A gestão precisa registrar uma entrada.</div>}</CardContent></Card>
  <div className="space-y-2"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold sm:text-base">Saldo disponível</h3><p className="text-xs text-muted-foreground">{availableStock.length} item(ns) com estoque</p></div><Button size="sm" variant="ghost" onClick={()=>setShowAllStock(!showAllStock)}>{showAllStock?<><ChevronUp className="mr-1 h-4 w-4"/>Ocultar zerados</>:<><ChevronDown className="mr-1 h-4 w-4"/>Ver todos</>}</Button></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{(showAllStock?stock:availableStock).map(x=><Card key={x.item_id} className={Number(x.current_stock)<=0?'opacity-60':''}><CardContent className="p-3"><p className="line-clamp-2 min-h-8 text-xs leading-tight text-muted-foreground">{x.name}</p><p className="mt-1 text-base font-bold sm:text-lg">{Number(x.current_stock).toLocaleString('pt-BR',{maximumFractionDigits:3})} <span className="text-[11px] font-normal">{x.unit}</span></p></CardContent></Card>)}</div>{!showAllStock&&availableStock.length===0&&<div className="rounded-lg border border-dashed p-4 text-center text-xs text-muted-foreground">Os itens com saldo aparecerão aqui após a primeira entrada.</div>}</div>
  <Card><CardHeader className="p-4 pb-2"><CardTitle className="text-base sm:text-lg">Meus lançamentos</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0 sm:p-4 sm:pt-2"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Insumo</TableHead><TableHead>Quantidade</TableHead><TableHead>Observação</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{history.length===0?<TableRow><TableCell colSpan={5} className="py-8 text-center text-sm text-muted-foreground">Nenhum consumo registrado.</TableCell></TableRow>:history.map(h=><TableRow key={h.id}><TableCell>{new Date(`${h.consumption_date}T12:00:00`).toLocaleDateString('pt-BR')}</TableCell><TableCell>{names[h.item_id]||'Insumo'}</TableCell><TableCell>{Number(h.quantity).toLocaleString('pt-BR',{maximumFractionDigits:3})}</TableCell><TableCell>{h.notes||'—'}</TableCell><TableCell>{h.status==='reversed'?'Estornado':'Registrado'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}
