// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://wabefmgfsatlusevxyfo.supabase.co';
const configuredSupabaseUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_URL = configuredSupabaseUrl || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (configuredSupabaseUrl && configuredSupabaseUrl !== DEFAULT_SUPABASE_URL) {
  console.warn(
    `⚠️ VITE_SUPABASE_URL (${configuredSupabaseUrl}) difere do projeto ativo (${DEFAULT_SUPABASE_URL}).`
  );
}

// Validação das variáveis de ambiente
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.error('❌ Erro: Variáveis de ambiente não configuradas:', missing.join(', '));
  console.error('📝 Configure as variáveis de ambiente no Vercel/Netlify:');
  console.error('   - VITE_SUPABASE_URL');
  console.error('   - VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error('   - VITE_SUPABASE_PROJECT_ID');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);